spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.myproject.firstproject.entity
  configuration.map-underscore-to-camel-case: true


pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

server:
  servlet:
    context-path: /firstproject
