spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.78.3.7:3306/firstproject
    username: root
    password: 13456
    driver-class-name: com.mysql.jdbc.Driver

    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

  redis:
    host: 120.78.3.7
    port: 6379
    password: leis666
    sentinel:
      master: mymaster
      nodes: 120.78.3.7:26379

server:
  port: 8070
  tomcat:
    max-threads: 2000
    max-connections: 2000

swagger2:
  host: localhost:8070
  url: http://localhost:8070/