spring:
  profiles:
    active: dev


mybatis:
  mapper-locations: classpath:public/mapper/*
  type-aliases-package: com.myproject.firstproject.entity

server:
  servlet:
    context-path: /firstproject
